# Generated by Django 4.0.4 on 2022-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spotted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('temperature', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='spotted',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='spotted',
            name='date',
            field=models.DateField(verbose_name='spotted on'),
        ),
    ]
