# Generated by Django 4.0.4 on 2022-04-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habitat_alter_spotted_options_alter_spotted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='habitats',
            field=models.ManyToManyField(to='main_app.habitat'),
        ),
    ]
